spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_catalog
    username: user
    password: password

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
